dependencies:
  - name: zero-scaler
    version: 0.0.1
    repository: file://../zero-scaler
    condition: zero-scaler.enabled

  - name: nginx-ingress
    alias: nginx-ingress-internal
    version: 0.31.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: nginx-ingress-internal.enabled

  - name: nginx-ingress
    alias: nginx-ingress-public
    version: 0.31.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: nginx-ingress-public.enabled

  - name: external-dns
    version: 1.0.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: external-dns.enabled

  - name: kube2iam
    version: 0.9.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: kube2iam.enabled

  - name: kubernetes-dashboard
    version: 0.8.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: kubernetes-dashboard.enabled

  - name: heapster
    version: 0.3.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: heapster.enabled

  - name: metrics-server
    version: 2.0.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: metrics-server.enabled

  - name: cluster-autoscaler
    version: 0.9.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: cluster-autoscaler.enabled

  - name: elastic-stack
    version: 1.1.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: elastic-stack.enabled

  - name: prometheus
    version: 8.3.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: prometheus.enabled

  - name: prometheus-adapter
    version: v0.2.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: prometheus-adapter.enabled

  - name: prometheus-cloudwatch-exporter
    version: 0.2.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: prometheus-cloudwatch-exporter.enabled

  - name: grafana
    version: 1.21.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: grafana.enabled
